services:
  server:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    # environment:

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - chroma_network
    restart: unless-stopped

volumes:
  chroma_data:

networks:
  chroma_network:
    name: chroma_network
    external: true