graph TD
    subgraph Email_Create_Batch_Pipeline
        A1(Start) --> A2(Get_Email_from_Dag_Run)
        A2 --> A3(Get_User_ID_for_Email)
        A3 --> A4(Create_DB_Session)
        A4 --> A5(Check_Gmail_OAuth2_Credentials)
        A5 --> A6(Get_Last_Read_Timestamp)
        A6 --> A7(Fetch_Emails_and_Create_Batches)
        A7 --> A8(Trigger_Email_Fetch_Pipeline)
        A8 -->|Failure| A9(Send_Failure_Notification)
    end

    subgraph Email_Fetch_Pipeline
        B1(Start) --> B2(Get_Batch_Data)
        B2 --> B3(Process_Emails_in_Batch_Mode)
        B3 --> B4(Upload_Raw_Data_to_GCS)
        B4 --> B5(Publish_Metrics)
        B5 --> B6(Data_Validation)
        B6 -->|Success| B7(Trigger_Preprocessing_Pipeline)
        B6 -->|Failure| B8(Send_Failure_Email)
    end

    subgraph Email_Preprocessing_Pipeline
        C1(Start) --> C2(Download_Raw_Data_from_GCS)
        C2 --> C3(Preprocess_Emails)
        C3 --> C4(Upload_Processed_Data_to_GCS)
        C4 --> C5(Trigger_Embedding_Pipeline)
        C5 -->|Failure| C6(Send_Failure_Email)
    end

    subgraph Email_Embedding_Pipeline
        D1(Start) --> D2(Download_Processed_Data_from_GCS)
        D2 --> D3(Generate_Embeddings)
        D3 --> D4(Upsert_Embeddings)
        D4 -->|Success| D5(Send_Success_Email)
        D4 -->|Failure| D6(Send_Failure_Email)
    end